/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.micro_leads.swigtest.test;

public class _test {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _test(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_test obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(_test obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigtest_native_swigJNI.delete__test(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFoo(byte value) {
    swigtest_native_swigJNI._test_foo_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public byte getFoo() {
    return (swigtest_native_swigJNI._test_foo_get(swigCPtr, this));
}

  public _test() {
    this(swigtest_native_swigJNI.new__test(), true);
  }

}
