/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.micro_leads.swigtest.test;

public class swigtest_native_swigJNI {
  public final static native void _test_foo_set(long jarg1, _test jarg1_, byte jarg2);
  public final static native byte _test_foo_get(long jarg1, _test jarg1_);
  public final static native long new__test();
  public final static native void delete__test(long jarg1);
  public final static native void test_set(long jarg1, _test jarg1_);
  public final static native long test_get();
}
