/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.micro_leads.swigtest.test;

public class swigtest_native_swigJNI {
  public final static native void foo_bar_set(long jarg1, foo jarg1_, byte jarg2);
  public final static native byte foo_bar_get(long jarg1, foo jarg1_);
  public final static native long new_foo();
  public final static native void delete_foo(long jarg1);
  public final static native void process(long jarg1, foo jarg1_, long jarg2, long jarg3);
}
