/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.micro_leads.swigtest.test;

public class swigtest_native_swig {
  public static void setTest(_test value) {
    swigtest_native_swigJNI.test_set(_test.getCPtr(value), value);
  }

  public static _test getTest() {
    long cPtr = swigtest_native_swigJNI.test_get();
    return (cPtr == 0) ? null : new _test(cPtr, false);
  }

}
